"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city.png  ExperimentsFNS/Output/city1.png  3 128 32 42
"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city.png  ExperimentsFNS/Output/city2.png  4 128 32 42
"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city.png  ExperimentsFNS/Output/city3.png  5 128 32 42
"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city2.png ExperimentsFNS/Output/cityb1.png 3 128 32 42
"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city2.png ExperimentsFNS/Output/cityb2.png 4 128 32 42
"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city2.png ExperimentsFNS/Output/cityb3.png 5 128 32 42
"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city3.png ExperimentsFNS/Output/cityc1.png 3 128 32 42
"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city3.png ExperimentsFNS/Output/cityc2.png 4 128 32 42
"../syntex.exe" verbose ExperimentsFNS/Output/db.csv FNS Samples/city3.png ExperimentsFNS/Output/cityc3.png 5 128 32 42
