call synth_skulls.cmd
call synth_wall.cmd
call synth_square_spiral.cmd
call synth_halls_and_foam.cmd
call synth_redfoam.cmd
call synth_bluehalls.cmd
call synth_sgraph.cmd
call synth_ball.cmd
call synth_solid_ball.cmd
call synth_city.cmd