"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Boulders.png ExperimentsCOC/Output/misc_Boulders.png 0.5 3 5 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/SimpleMaze.png ExperimentsCOC/Output/misc_SimpleMaze.png 1.0 2 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Cave.png ExperimentsCOC/Output/misc_Cave.png 1.0 3 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Caves.png ExperimentsCOC/Output/misc_Caves.png 1.0 3 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Chess.png ExperimentsCOC/Output/misc_Chess.png 1.0 2 1 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/LessRooms.png ExperimentsCOC/Output/misc_LessRooms.png 1.0 3 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Maze.png ExperimentsCOC/Output/misc_Maze.png 1.0 3 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/River.png ExperimentsCOC/Output/misc_River.png 1.0 3 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Rooms.png ExperimentsCOC/Output/misc_Rooms.png 1.0 3 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/SimpleRooms.png ExperimentsCOC/Output/misc_SimpleRooms.png 1.0 3 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/ThickWalls.png ExperimentsCOC/Output/misc_ThickWalls.png 1.0 3 10 64 64 -1
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/CaveMaze.png ExperimentsCOC/Output/misc_CaveMaze.png 1.0 3 10 64 64 -1