"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Boulders.png ExperimentsCOC/Output/misc_Boulders.gif 0.5 3 5 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/SimpleMaze.png ExperimentsCOC/Output/misc_SimpleMaze.gif 1.0 2 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Cave.png ExperimentsCOC/Output/misc_Cave.gif 1.0 3 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Caves.png ExperimentsCOC/Output/misc_Caves.gif 1.0 3 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Chess.png ExperimentsCOC/Output/misc_Chess.gif 1.0 2 5 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/LessRooms.png ExperimentsCOC/Output/misc_LessRooms.gif 1.0 3 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Maze.png ExperimentsCOC/Output/misc_Maze.gif 1.0 3 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/River.png ExperimentsCOC/Output/misc_River.gif 1.0 3 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/Rooms.png ExperimentsCOC/Output/misc_Rooms.gif 1.0 3 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/SimpleRooms.png ExperimentsCOC/Output/misc_SimpleRooms.gif 1.0 3 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/ThickWalls.png ExperimentsCOC/Output/misc_ThickWalls.gif 1.0 3 10 64 64 42
"../syntex.exe" verbose ExperimentsCOC/Output/db.csv COC SamplesBnW/CaveMaze.png ExperimentsCOC/Output/misc_CaveMaze.gif 1.0 3 10 64 64 42